-- Seed: 30 .cu sources found under c:\dev (Everything index, 2026-10-03).
-- status = 'unverified' for all; promote only after a logged run + verdict.
INSERT OR IGNORE INTO kernels (kernel_id, repo, source_path, dll_path, category, notes) VALUES
('cu_vision_lite',        'cu_vision_lite',      'c:\dev\cu_vision_lite\csrc\cu_vision_lite.cu',            'c:\dev\cu_vision_lite\cu_vision_lite_sm89.dll', 'vision',   'trunk; also cu_vision_lite.dll'),
('cu_vision_features',    'cu_vision_lite',      'c:\dev\cu_vision_lite\csrc\cu_vision_features.cu',        NULL, 'vision',   'no standalone DLL in tree'),
('cu_geopin_solver',      'cu_vision_lite',      'c:\dev\cu_vision_lite\csrc\cu_geopin_solver.cu',          NULL, 'tracking', 'pin/patch tracker + PnP; duplicate source in cuda_pin_tracker'),
('cu_geopin_solver_pt',   'cuda_pin_tracker',    'c:\dev\cuda_pin_tracker\csrc\cu_geopin_solver.cu',        NULL, 'tracking', 'duplicate of cu_vision_lite copy; diff before consolidating'),
('cu_skeleton_kinematics','cu_vision_lite',      'c:\dev\cu_vision_lite\csrc\cu_skeleton_kinematics.cu',    'c:\dev\cu_vision_lite\cu_skeleton_kinematics.dll', 'pose', NULL),
('cu_bowling_tracker',    'cu_vision_lite',      'c:\dev\cu_vision_lite\csrc\cu_bowling_tracker.cu',        NULL, 'tracking', 'ball drifts after ~5s (operator, 09-25)'),
('cu_dense_stereo',       'cu_vision_lite',      'c:\dev\cu_vision_lite\csrc\cu_dense_stereo.cu',           'c:\dev\cu_vision_lite\cu_dense_stereo.dll', 'stereo', 'operator verdict: garbage (09-26)'),
('cu_object_clear_ops',   'cu_vision_lite',      'c:\dev\cu_vision_lite\csrc\cu_object_clear_ops.cu',       NULL, 'vision',   'dormant'),
('cu_dxgi_capture',       'cu_vision_lite',      'c:\dev\cu_vision_lite\csrc\cu_dxgi_capture.cu',           NULL, 'capture',  NULL),
('adaptive_delta_fused',  'screen_agent_cuda',   'c:\dev\screen_agent_cuda\csrc\adaptive_delta_fused.cu',   NULL, 'diff',     'cu_adaptive_delta_fused; 16x16 MSE'),
('dxgi_ocr_tensor',       'screen_agent_cuda',   'c:\dev\screen_agent_cuda\csrc\dxgi_ocr_tensor.cu',        NULL, 'capture',  NULL),
('screen_kernel',         'screen_agent_cuda',   'c:\dev\screen_agent_cuda\csrc\screen_kernel.cu',          NULL, 'capture',  NULL),
('dxgi_cuda_delta',       'dxgi-cuda-frame-delta','c:\dev\dxgi-cuda-frame-delta\dxgi_cuda_delta.cu',        NULL, 'diff',     NULL),
('object_clear',          'object_clear_cuda',   'c:\dev\object_clear_cuda\csrc\object_clear.cu',           NULL, 'vision',   'SAM + LaMa inpaint path'),
('arrow_sq8_search',      'turbo-cuda-duckdb',   'c:\dev\turbo-cuda-duckdb\csrc\arrow_sq8_search.cu',       NULL, 'vector',   NULL),
('vector_ops',            'turbo-cuda-duckdb',   'c:\dev\turbo-cuda-duckdb\csrc\vector_ops.cu',             NULL, 'vector',   NULL),
('diff_embed_kernel_tc',  'turbo-cuda-duckdb',   'c:\dev\turbo-cuda-duckdb\csrc\diff_embed_kernel.cu',      NULL, 'diff',     'text/embedding diff; duplicate in diff_embed_cuda'),
('diff_embed_kernel',     'diff_embed_cuda',     'c:\dev\diff_embed_cuda\csrc\diff_embed_kernel.cu',        NULL, 'diff',     'backs workspace_cuda_diff (AST token / cosine shift), NOT frame diff'),
('intent_telepathy',      'turbo-cuda-duckdb',   'c:\dev\turbo-cuda-duckdb\csrc\intent_telepathy.cu',       NULL, 'misc',     NULL),
('neuromotor_clc',        'turbo-cuda-duckdb',   'c:\dev\turbo-cuda-duckdb\csrc\neuromotor_clc.cu',         NULL, 'misc',     NULL),
('continuous_stream_daemon','vram_swap_cuda',    'c:\dev\vram_swap_cuda\csrc\continuous_stream_daemon.cu',  NULL, 'misc',     NULL),
('native_audio_kernel',   'vram_swap_cuda',      'c:\dev\vram_swap_cuda\csrc\native_audio_kernel.cu',       NULL, 'audio',    NULL),
('turbo_vector_kernel',   'vram_swap_cuda',      'c:\dev\vram_swap_cuda\csrc\turbo_vector_kernel.cu',       NULL, 'vector',   NULL),
('unified_offload_engine','vram_swap_cuda',      'c:\dev\vram_swap_cuda\csrc\unified_offload_engine.cu',    NULL, 'misc',     NULL),
('vram_swap_kernel',      'vram_swap_cuda',      'c:\dev\vram_swap_cuda\csrc\vram_swap_kernel.cu',          NULL, 'misc',     NULL),
('audio_vad_gate',        'speech-mcp-server',   'c:\dev\speech-mcp-server\csrc\audio_vad_gate.cu',         NULL, 'audio',    NULL),
('kokoro_mel_bridge',     'speech-mcp-server',   'c:\dev\speech-mcp-server\csrc\kokoro_mel_bridge.cu',      NULL, 'audio',    NULL),
('band_dsp_cuda',         'CGMusicalComposition','c:\dev\CGMusicalComposition\csrc\band_dsp_cuda.cu',       NULL, 'audio',    NULL),
('faceswap_kernels',      'faceswap_engine',     'c:\dev\faceswap_engine\cuda\faceswap_kernels.cu',         NULL, 'vision',   NULL),
('pdf_preview_cuda',      'pdf_preview_cuda',    'c:\dev\pdf_preview_cuda\pdf_preview_cuda.cu',             NULL, 'misc',     NULL);
